### ISSUE TITLE
lightnodepro not installing as hid i think

### ISSUE THREAD

**Issue by rikis156** [Legion2/CorsairLightingProtocol#33]
**Describe the problem**
i have the same problem as #17 
it did install correctly the first time but it did not work so i uninstalled it and re-plugged my arduino and now it just says unknown device under com ports

**Screenshots**
![b5f22958ff1c4d6d6abb0082fae8af93](https://user-images.githubusercontent.com/53133445/61586881-eef7f500-ab7d-11e9-89e2-e9f10a31177a.png)
![f46d9e4192abb64675bff52f258b9fa4](https://user-images.githubusercontent.com/53133445/61586887-fcad7a80-ab7d-11e9-9925-874b93192e71.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Board: Pro Micro
 - IDE: Arduino IDE
 - Version: 0.3.0 all the way to 0.5.0
 - Sketch:  LightingNodePRO

**Code changes**
Did you changed the code of the library or the sketch?
no i did not edit anythning

**Comment by rikis156** [comment]
################################################################################
################################## Pro Micro ###################################
################################################################################
promicrocpl.name=CLP SparkFun Pro Micro

promicrocpl.upload.tool=avrdude
promicrocpl.upload.protocol=avr109
promicrocpl.upload.maximum_size=28672
promicrocpl.upload.maximum_data_size=2560
promicrocpl.upload.speed=57600
promicrocpl.upload.disable_flushing=true
promicrocpl.upload.use_1200bps_touch=true
promicrocpl.upload.wait_for_upload_port=true

promicrocpl.bootloader.tool=avrdude
promicrocpl.bootloader.unlock_bits=0x3F
promicrocpl.bootloader.lock_bits=0x2F
promicrocpl.bootloader.low_fuses=0xFF
promicrocpl.bootloader.high_fuses=0xD8

promicrocpl.build.board=AVR_PROMICRO
promicrocpl.build.core=arduino:arduino
promicrocpl.build.variant=promicro
promicrocpl.build.mcu=atmega32u4
promicrocpl.build.usb_product="Lighting Node PRO"
promicrocpl.build.vid=0x1b1c
promicrocpl.build.extra_flags={build.usb_flags}

######################### Pro Micro 3.3V / 8MHz ################################
promicrocpl.menu.cpu.8MHzatmega32U4=ATmega32U4 (3.3V, 8 MHz)

promicrocpl.menu.cpu.8MHzatmega32U4.build.pid.0=0x0c0b
promicrocpl.menu.cpu.8MHzatmega32U4.build.pid.1=0x0c0b
promicrocpl.menu.cpu.8MHzatmega32U4.build.pid=0x0c0b
promicrocpl.menu.cpu.8MHzatmega32U4.build.f_cpu=8000000L

promicrocpl.menu.cpu.8MHzatmega32U4.bootloader.extended_fuses=0xFE
promicrocpl.menu.cpu.8MHzatmega32U4.bootloader.file=caterina/Caterina-promicro8.hex


############################# Pro Micro 5V / 16MHz #############################
promicrocpl.menu.cpu.16MHzatmega32U4=ATmega32U4 (5V, 16 MHz)

promicrocpl.menu.cpu.16MHzatmega32U4.build.pid.0=0x0c0b
promicrocpl.menu.cpu.16MHzatmega32U4.build.pid.1=0x0c0b
promicrocpl.menu.cpu.16MHzatmega32U4.build.pid=0x0c0b
promicrocpl.menu.cpu.16MHzatmega32U4.build.f_cpu=16000000L

promicrocpl.menu.cpu.16MHzatmega32U4.bootloader.extended_fuses=0xCB
promicrocpl.menu.cpu.16MHzatmega32U4.bootloader.file=caterina/Caterina-promicro16.hex
promicrocpl.build.extra_flags={build.usb_flags} '-DSERIAL_NUMBER="FB66DF55421900F5"'


################################################################################


if it may be of use :)

**Comment by Legion2** [comment]
I don't understand what you mean with unknown COM Port. After you uploaded the sketch, the COM port changes, so if you what to upload again, you have to select the new COM port in Arduino IDE.

The HID is set like you can see in SIV, there is only the manufacturer unknown, because Pro Micro does not set it. You can add `promicroclp.build.usb_manufacturer="Corsair"` to the `boards.local.txt`, that should fix that.

**Comment by rikis156** [comment]
i have added that but still dont show up in icue and last night i did get it to show up as an hid but it still wont work in icue

**Comment by Legion2** [comment]
You have SIV, so go in SIV to LINK->LINK Status there should be CLNP, click on it and post screenshot here

**Comment by rikis156** [comment]
![8d612bc4eec306c8ab72e676e6b8716e](https://user-images.githubusercontent.com/53133445/61590442-b5dd7600-abb9-11e9-85e6-0404a93e3173.png)

i have two CLNP showing and both say the same

**Comment by Legion2** [comment]
did you tried to restart your PC?

**Comment by Legion2** [comment]
You can also try the solution from #12

**Comment by rikis156** [comment]
i restarted my pc and got a different screen in SIV but it still did not show up in iCUE and yes i have tried #12

**Comment by rikis156** [comment]
![1bc5bdb28cf01b545c8921f771b1630b](https://user-images.githubusercontent.com/53133445/61590967-4cad3100-abc0-11e9-8675-f7174cf76fdb.png)
it looks like this now

**Comment by Legion2** [comment]
use v0.5.0, comment the line `disableBuildInLEDs();` in the sketch and upload.
Then you should see the RX and TX led of the board blinking.

**Comment by rikis156** [comment]
i have a yellow light that is flashing

**Comment by Legion2** [comment]
i don't known if it's the problem, but maybe the EEPROM of arduino contains bad data. To test this use the SingleStripLightingNodePRO.ino and change `USE_EEPROM true` to false

**Comment by rikis156** [comment]
no change  only the yellow light that do anything

**Comment by Legion2** [comment]
how did you installed this library, are you sure it's v0.5.0?

**Comment by rikis156** [comment]
drag and drop to libraries in the arduino IDE folder

**Comment by rikis156** [comment]
![8be175e1ec84c3f46d3d5de5418cb8ef](https://user-images.githubusercontent.com/53133445/61591340-37d39c00-abc6-11e9-99b6-35116356bc0b.png)
not sure if this says anything but it dose not show up under hid in device manager as it did before

**Comment by Legion2** [comment]
upload `DeviceIDTool.ino` to set a Device ID with serial monitor

**Comment by rikis156** [comment]
Ok i did that but still nothing, rightnow only if i restart my pc it shows as a hid i the device manager if i reupload to the arduino it goes away

**Comment by Legion2** [comment]
use different usb port?

**Comment by Legion2** [comment]
use SIV to get the USB and HID inforamtion(in USB Bus click on the Port button of the LNP)

**Comment by Legion2** [comment]
is see you called the id in `boards.local.txt` `promicrocpl` and not `promicroclp`, maybe there is somewhere else a typo.

**Comment by rikis156** [comment]
not sure where that would be, i have not written anytning else than boards.local.txt and i did fix that promicroclp insted of promicrocpl but it acts like it has always done

**Comment by Legion2** [comment]
after you changed boards.local.txt you must restart Arduino IDE

**Comment by Legion2** [comment]
In SIV it should look something like this
![image](https://user-images.githubusercontent.com/12752323/61592330-445df180-abd2-11e9-970d-e14fe33c25b1.png)
![image](https://user-images.githubusercontent.com/12752323/61592348-796a4400-abd2-11e9-896c-f4a9c0b8dccb.png)

**Comment by rikis156** [comment]
![042be49b96562f5b13719f029a81bf27](https://user-images.githubusercontent.com/53133445/61593055-dcf86f80-abda-11e9-9281-9051e9a54acd.png)

**Comment by rikis156** [comment]
the only thing i can see that is different is Device USB V2.00  LangID 0409 1 Class 0.0.0 Class 0 (00) SubClass 0 (00) Protocol 0 (00)  Maximum Packet Size 64 (EP0)  Configurations 1  Descriptors 14

**Comment by Legion2** [comment]
you can add some debug code to the `loop` and see if it's printed to the serial monitor

**Comment by rikis156** [comment]
it does :(

**Comment by Legion2** [comment]
so you have serial output every time the loop gets called, but iCUE and SIV Link Status does not show good output?

**Comment by rikis156** [comment]
![69548196cdacf76237f850623f38c848](https://user-images.githubusercontent.com/53133445/61594180-db35a880-abe8-11e9-8e2a-f251353f16d4.png)
yes it seems so

**Comment by Legion2** [comment]
you are using an old Arduino IDE version, can you update?

**Comment by Legion2** [comment]
Later this day i will create a debug sketch, that will give us more information.

**Comment by rikis156** [comment]
i will update

**Comment by rikis156** [comment]
In file included from C:\Program Files (x86)\Arduino\libraries\CorsairLightingProtocol-dev\src/FastLEDController.h:19:0,

                 from C:\Program Files (x86)\Arduino\libraries\CorsairLightingProtocol-dev\src/CorsairLightingNodePRO.h:20,

                 from C:\Program Files (x86)\Arduino\libraries\CorsairLightingProtocol-dev\examples\DebugSketch\DebugSketch.ino:16:

C:\Program Files (x86)\Arduino\libraries\FastLED-master/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.000

 #    pragma message "FastLED version 3.002.000"

                     ^

DebugSketch:31:18: error: 'PRINT_LOOP' was not declared in this scope

 bool printLoop = PRINT_LOOP;

                  ^

DebugSketch:32:20: error: 'PRINT_UPDATE' was not declared in this scope

 bool printUpdate = PRINT_UPDATE;

                    ^

Multiple libraries were found for "FastLED.h"
 Used: C:\Program Files (x86)\Arduino\libraries\FastLED-master
 Not used: D:\Dropbox\Arduino\libraries\arduino_883197
exit status 1
'PRINT_LOOP' was not declared in this scope




i get this error while i try to compile

**Comment by Legion2** [comment]
you use the Arduino IDE, so you must define all the build options from the board.txt in the boards.local.txt. the DebugSketch require more build options then the normal sketch, add this extra options to you boards.local.txt.

**Comment by rikis156** [comment]
for some reason when i uploded the DebugSketch.ino it all started to work for me 

and to anyone else that is using a pro micro this is the bord.text that made it work for me

################################################################################
################################## Pro Micro ###################################
################################################################################
promicroclp.name=CLP SparkFun Pro Micro

promicroclp.upload.tool=avrdude
promicroclp.upload.protocol=avr109
promicroclp.upload.maximum_size=28672
promicroclp.upload.maximum_data_size=2560
promicroclp.upload.speed=57600
promicroclp.upload.disable_flushing=true
promicroclp.upload.use_1200bps_touch=true
promicroclp.upload.wait_for_upload_port=true

promicroclp.bootloader.tool=avrdude
promicroclp.bootloader.unlock_bits=0x3F
promicroclp.bootloader.lock_bits=0x2F
promicroclp.bootloader.low_fuses=0xFF
promicroclp.bootloader.high_fuses=0xD8

promicroclp.build.board=AVR_PROMICRO
promicroclp.build.core=arduino:arduino
promicroclp.build.variant=promicro
promicroclp.build.mcu=atmega32u4
promicroclp.build.usb_product="Lighting Node PRO"
promicroclp.build.usb_manufacturer="Corsair"
promicroclp.build.vid=0x1b1c
promicroclp.build.extra_flags={build.usb_flags} '-DSERIAL_NUMBER="FB66DF55421900F5"'

######################### Pro Micro 3.3V / 8MHz ################################
promicroclp.menu.cpu.8MHzatmega32U4=ATmega32U4 (3.3V, 8 MHz)

promicroclp.menu.cpu.8MHzatmega32U4.build.pid.0=0x0c0b
promicroclp.menu.cpu.8MHzatmega32U4.build.pid.1=0x0c0b
promicroclp.menu.cpu.8MHzatmega32U4.build.pid=0x0c0b
promicroclp.menu.cpu.8MHzatmega32U4.build.f_cpu=8000000L

promicroclp.menu.cpu.8MHzatmega32U4.bootloader.extended_fuses=0xFE
promicroclp.menu.cpu.8MHzatmega32U4.bootloader.file=caterina/Caterina-promicro8.hex


############################# Pro Micro 5V / 16MHz #############################
promicroclp.menu.cpu.16MHzatmega32U4=ATmega32U4 (5V, 16 MHz)

promicroclp.menu.cpu.16MHzatmega32U4.build.pid.0=0x0c0b
promicroclp.menu.cpu.16MHzatmega32U4.build.pid.1=0x0c0b
promicroclp.menu.cpu.16MHzatmega32U4.build.pid=0x0c0b
promicroclp.menu.cpu.16MHzatmega32U4.build.f_cpu=16000000L

promicroclp.menu.cpu.16MHzatmega32U4.bootloader.extended_fuses=0xCB
promicroclp.menu.cpu.16MHzatmega32U4.bootloader.file=caterina/Caterina-promicro16.hex
promicroclp.build.build.extra_flags={build.usb_flags} '-DSERIAL_NUMBER="FB66DF55421900F5"'


################################################################################


 And Legion2  you the legend man thanks for all the help you have provided me :)

**Comment by Legion2** [comment]
But you are now using the normal sketch like before? You uploaded the DebugSketch successfully and then switch back to the other sketch, or not?

**Comment by rikis156** [comment]
iam not using the DebugSketch any more but i have some flicker in the light but that could be my connections but it works

**Comment by Legion2** [comment]
I'm asking, because i want to understand the problem, which now is somehow fixed. If I understand it i can improve this project so others don't run into the same problem.
